# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [1]:
import numpy
from keras.datasets import cifar100
import numpy as np
np.random.seed(100)

Using TensorFlow backend.


# 資料準備

In [2]:
(X_train, y_train), (X_val, y_val) = cifar100.load_data()

169009152/169001437 [==============================] - 45s 0us/step


# Image normalize 

In [3]:
X_train_nor = X_train.astype('float32')/ 255.
X_val_nor  = X_val.astype('float32')/ 255.

# 轉換label 為OneHot Encoding

In [5]:
from keras.utils import np_utils
y_train_onehot = np_utils.to_categorical(y_train)
y_val_onehot = np_utils.to_categorical(y_val)

In [6]:
print(y_train_onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
